#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_PSA_CRYPTO_PRESENT
#define SL_CATALOG_SE_CPC_PRIMARY_PRESENT
#define SL_CATALOG_SE_MANAGER_PRESENT

#endif // SL_COMPONENT_CATALOG_H
